<div class="row">
	<div class=col-md-1></div>
	<div class=col-md-10>
		<img src="images/prevenir/terminos.png" style="max-width: 100%; width: 100%;">
	</div>
	<div class=col-md-1></div>
</div>

<div class="contenido"> 

	<div class="row"> 
		<div class=col-md-1></div>
		<div class="col-md-10"> 
			<h2 class="text-center tituloPrincipal">Términos y Condiciones</h2>

			<p>Para recibir descuentos debe estar inscrito y sus datos diligenciados al 100%, Los descuentos deberá ser redimido a nuestros terceros para confirmar día fecha y hora de su requerimiento. No tenemos límite de descuentos por persona. El descuento se enviará vía mail, WhatsApp, mensaje de texto o en su defecto se le llamara personalmente para conocimiento del solicitante. Para preguntas o reclamos (PQRS) se debe ingresar a www.prevenirexpress.com en espacio PQRS o al correo clientes@prevenirexpress.com Se debe enviar un e-mail ha solicitado su requerimiento o comunicarse a los teléfonos (2) 7290038 o wpp 310 4351937, 3172645522, o al correo admin@prevenirexpress.com. </p>

			<small>* Los descuentos los aplica la entidad jurídica o natural de acuerdo a sus condiciones y restricciones.</small>
			<small>*Aplican condiciones y restricciones a todos los descuentos</small>

			<p>GRUPO PREVENIR EXPRESS Sas. Es un enlace entre el usuario y el tercero para que apliquen los descuentos del servicio y NO se hace responsable de incumplimientos, malos procedimientos pero estará muy atento a las sugerencia quejas y reclamos para dar un buen servicio </p>

			<h2 class="text-center tituloPrincipal">Tratamientos De Datos Privacidad Y Confidencialidad</h2>

			<h3 class="subtitulo">Tratamiento De Datos Personales</h3>

			<p>GRUPO PREVENIR EXPRESS sas. (En adelante, “GRUPO PREVENIR o GP"), identificada con NIT 900690163-6, ubicada en la carrera 29 No 17 – 89 segundo piso, Pasto Nariño, con número de teléfonos (2) 7290038 Wpp 310 4351937, 3172645522, E-mail admin@prevenirexpress.com, es el titular del tratamiento de los datos personales de las personas naturales usuarias del sitio http://www.prevenirexpress.com. Debido a la actividad comercial que desarrolla GP, y dando cumplimiento al Decreto 1377 de 2013, les informamos a los titulares de los datos personales que GP lleva a cabo los siguientes tipos de Tratamiento sobre sus datos personales. </p>
			<p>1. Protegiendo: Sus derechos frente al Tratamiento de sus datos personales. GP está comprometido con proteger su privacidad y garantizar sus derechos al habeas data para que Usted pueda conocer, actualizar y rectificar los datos personales que administre GRUPO PREVENIR. Esta Política de Tratamiento de Datos es referente al uso que GRUPO PREVENIR ESPRESS sas. Le dará a los datos personales que reposen en sus registros de conformidad con lo establecido en la ley 1581 de 2012 y el Decreto 1377 de 2013. </p>
			<p>1.1 FINALIDAD DE LA BASE DE DATOS. La base de datos tiene como finalidades principales informarle sobre los servicios que prestamos en primera persona y/o con terceros, para fines comerciales, administrativos y publicitarios y contacto frente a los titulares de los mismos.  </p>
			<p>1.2 DATOS PERSONALES. La información objeto de tratamiento por parte de GRUPO PREVENIR EXPRESS sas. En adelante en este documento “Datos personales”, es aquella que suministran los Titulares, cuando acceden a sus bienes y/o servicios, o con ocasión de los mismos, tales como: nombre, apellidos, identificación, edad, sexo, teléfono, dirección física y electrónica, país, ciudad y demás datos sensibles pero necesarios que le sean solicitados en el proceso de registro, los cuales en ningún caso serán manipulados ni entregado a terceros sin su autorización como lo dispone la ley. GRUPO PREVENIR ESPRESS sas. Se reserva el derecho de modificar esta política sin previo aviso. Los cambios realizados no afectarán las obligaciones ni seguridad exigida por la normatividad vigente. Los cambios realizados podrán ser anunciados a los usuarios a través de la página web y/o a través de correo electrónico, sin embargo usted debe comprobar nuestro sitio web para ver los cambios recientes. Dado el carácter vinculante de los términos y condiciones, es responsabilidad única del Usuario revisar los términos vigentes en cada momento. La presente política se publica el marzo del 2019. </p>

			<h3 class="subtitulo">2. INFORMACIÓN CONTENIDA EN EL PORTAL WEB</h3>
			<p>2.1 Propiedad del contenido del Portal – Copyright El portal www.prevenirexpress.com (en adelante el “Portal”) es de propiedad de GRUPO PREVENIR EXPRESS sas. (En adelante, “GRUPO PREVENIR o GP”). Y su App (En adelante “GRUPO PREVENIR o DESCUENTOS MEDICOS”) El acceso, participación y uso del Portal está regido por los Términos y Condiciones y las Políticas de Tratamiento de la Información que se incluyen a continuación y se entienden conocidos y aceptados por el usuario del Portal. Se entenderá como usuario aquella persona que acceda, participe o use el Portal (en adelante, el “Usuario”) y/o el Tercero quien es la entidad Jurídica o Natural quien presta sus actividades comerciales a través de estos portales ofertando sus productos o servicios con un descuento y trato Preferencial al Usuario (En adelante el “usuario”), ello implica su adhesión plena e incondicional a estos términos y condiciones y las Políticas de Tratamiento de la Información aquí contempladas. Si en cualquier momento el Usuario y/o el tercero no estuviera de acuerdo total o parcialmente con estos Términos y Condiciones y las Políticas de Tratamiento de la Información, deberá abstenerse inmediatamente de usar este Portal en cualquiera de sus partes o secciones, en caso contrario cualquier uso de los mismos presumirá que el Usuario acepta sin reserva los Términos y Condiciones de uso y las Políticas de Tratamiento de la Información bajo su total responsabilidad. </p>
			<p>Esta página de Internet y su App son de propiedad del GRUPO PREVENIR EXPRESS sas. Quien es titular de los derechos de autor y de propiedad intelectual del contenido textual, auditivo y gráfico de este Portal y ostenta los derechos de explotación de éstos a través de acuerdos con terceros, quienes conceden el uso de los mismos. La aceptación de los presentes Términos y Condiciones y las Políticas de Tratamiento de la Información no implica en ningún caso la adquisición por parte del Usuario y/o el tercero de los derechos de propiedad intelectual o industrial relacionados con el Portal o con su contenido. GRUPO PREVENIR no concede licencia o autorización de uso alguna sobre el Portal y su contenido, por lo tanto está prohibida su reproducción total o parcial, su traducción, inclusión, transmisión, almacenamiento o acceso a través de medios analógicos, digitales o de cualquier otro sistema o tecnología creada o por crearse, sin autorización previa y escrita de GRUPO PREVENIR. Todo nombre, marca, logo, texto, gráfico, dibujo, fotografía, video, sonido y en general todo contenido de este Portal está protegido por derechos de propiedad intelectual así como por cualquier otro derecho de propiedad conforme lo permitan las leyes aplicables. La titularidad de tales derechos recae en cabeza de GRUPO PREVENIR o de terceros que por mandato legal o autorización expresa han conferido a GRUPO PREVENIR el derecho al uso o explotación de los mismos. </p>
			<p>Teniendo en cuenta la posibilidad del Usuario de incluir en el Portal: videos, fotos y/ o imágenes y/o textos y/u otro tipo de material de titularidad del Usuario o bien por éste de titularidad de un tercero, se deja expresamente establecido que al incluirlo en el Portal se considerará que el Usuario o el tercero concede a GRUPO PREVENIR en forma permanente, una licencia de uso gratuita, No exclusiva, para la reproducción, adaptación, compilación, almacenamiento y distribución de los contenidos por él suministrados a través de esta página de Internet y/o su App sin derecho a percibir contraprestación, remuneración, retribución o reclamo posterior alguno, cualquiera sea su tipo o índole. GRUPO PREVENIR podrá a su vez hacer cualquier tipo de uso de dicho material, en virtud de la licencia de uso así concedida. En tal sentido el Usuario reconoce que GRUPO PREVENIR podrá realizar la reproducción y sincronización del contenido publicado, en cualquier formato, conocido o por conocerse. Así mismo, la comunicación pública o distribución de dicho contenido se podrá realizar a través de cualquier medio existente o por desarrollarse, incluyendo, pero sin limitarse a: Internet, descargas móviles, descargas desde la App del GRUPO PREVENIR, televisión, abierta o cerrada, Home Video y DVD. Consecuentemente, GRUPO PREVENIR queda en plena libertad de reproducir, distribuir, fijar, comunicar públicamente, transformar, comercializar y realizar cualquier negociación plena y sin ninguna limitación en relación con los derechos patrimoniales sobre cualquier contenido cargado o publicado por algún Usuario del Portal. </p>
			<p>2.2 El Usuario garantiza que los contenidos suministrados son de su autoría, que no está violando derechos de autor de terceras personas y que mantendrá indemne a GRUPO PREVENIR y a sus sub licenciatarios frente a cualquier reclamación que se presente con ocasión de su uso. Así mismo, el Usuario se obliga a no cargar ningún contenido que contenga material cuya utilización por GRUPO PREVENIR le pueda generar algún tipo de perjuicio a éste último.  </p>
			<p>2.3 El acceso a el Portal por parte del Usuario tiene carácter libre; no obstante algunos de los servicios y contenidos ofrecidos por GRUPO PREVENIR o por terceros a través del Portal tales como: Señal en vivo, videos y audios por demanda para entretenimiento, humor, cultura, actualidad, opinión, entre otros, pueden encontrarse sujetos a pago, así como al registro y autenticación del Usuario y/o terceros en la forma que se determine en los correspondientes Términos y Condiciones. Queda prohibida la contratación de productos o servicios a través del Portal por parte de menores de edad, debiendo éstos obtener debidamente y con anterioridad, el consentimiento de sus padres, tutores o representantes legales, los cuales serán considerados como responsables de los actos que lleven a cabo los menores a su cargo, conforme a la normatividad vigente.   </p>
			<p>2.4 Por el hecho de ingresar al Portal y para garantizar el buen y adecuado uso del mismo, el Usuario reconoce en cabeza de GRUPO PREVENIR: (i) El derecho de actualizar, modificar o eliminar en cualquier tiempo y por cualquier razón sin previo aviso, tanto la información contenida en éste portal Web, así como estos términos y condiciones, pudiendo incluso limitar o no permitir el acceso a dicha información; (ii) El derecho de negar el registro a cualquier persona, en cualquier momento y por cualquier razón. (iii) El derecho de incluir o no en el Portal el material recibido de los usuarios a su criterio. En el caso de incluirlo, podrá mantener en los Portales dicho material por el lapso que considere pertinente o modificarlo. (iv) Remover, sin que sea obligatorio, contenidos que a juicio de GRUPO PREVENIR sean ilegales, ofensivos, difamatorios o que de cualquier otra forma violen éstos Términos y Condiciones. Así mismo, podrán ser retirados los contenidos que violen derechos intelectuales, ya sean de GRUPO PREVENIR o de un tercero, a solicitud de éste. (v) Utilizar la información personal y/o contenidos suministrados por los Usuarios y/o terceos de acuerdo con los Términos y Condiciones del Portal y las Políticas de Tratamiento de la Información. </p>

		</div>
		<div class=col-md-1></div>
	</div>



</div>